package rwcjom.awit.com.rwcjo_m.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BASE_PNT_INFO.
 */
public class BasePntInfo {

    private String basepntid;
    private String basepntname;
    private String basepntcode;
    private String basepnthigh;
    private String basepntnum;
    private String basepntvar;
    private String f_sectid;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BasePntInfo() {
    }

    public BasePntInfo(String basepntid) {
        this.basepntid = basepntid;
    }

    public BasePntInfo(String basepntid, String basepntname, String basepntcode, String basepnthigh, String basepntnum, String basepntvar, String f_sectid) {
        this.basepntid = basepntid;
        this.basepntname = basepntname;
        this.basepntcode = basepntcode;
        this.basepnthigh = basepnthigh;
        this.basepntnum = basepntnum;
        this.basepntvar = basepntvar;
        this.f_sectid = f_sectid;
    }

    public String getBasepntid() {
        return basepntid;
    }

    public void setBasepntid(String basepntid) {
        this.basepntid = basepntid;
    }

    public String getBasepntname() {
        return basepntname;
    }

    public void setBasepntname(String basepntname) {
        this.basepntname = basepntname;
    }

    public String getBasepntcode() {
        return basepntcode;
    }

    public void setBasepntcode(String basepntcode) {
        this.basepntcode = basepntcode;
    }

    public String getBasepnthigh() {
        return basepnthigh;
    }

    public void setBasepnthigh(String basepnthigh) {
        this.basepnthigh = basepnthigh;
    }

    public String getBasepntnum() {
        return basepntnum;
    }

    public void setBasepntnum(String basepntnum) {
        this.basepntnum = basepntnum;
    }

    public String getBasepntvar() {
        return basepntvar;
    }

    public void setBasepntvar(String basepntvar) {
        this.basepntvar = basepntvar;
    }

    public String getF_sectid() {
        return f_sectid;
    }

    public void setF_sectid(String f_sectid) {
        this.f_sectid = f_sectid;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
