package rwcjom.awit.com.rwcjo_m.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BRG_INFO.
 */
public class BrgInfo {

    private String faceid;
    private String structname;
    private String piernum;
    private String beamspan;
    private String beamtype;
    private String remark;

    public BrgInfo() {
    }

    public BrgInfo(String faceid) {
        this.faceid = faceid;
    }

    public BrgInfo(String faceid, String structname, String piernum, String beamspan, String beamtype, String remark) {
        this.faceid = faceid;
        this.structname = structname;
        this.piernum = piernum;
        this.beamspan = beamspan;
        this.beamtype = beamtype;
        this.remark = remark;
    }

    public String getFaceid() {
        return faceid;
    }

    public void setFaceid(String faceid) {
        this.faceid = faceid;
    }

    public String getStructname() {
        return structname;
    }

    public void setStructname(String structname) {
        this.structname = structname;
    }

    public String getPiernum() {
        return piernum;
    }

    public void setPiernum(String piernum) {
        this.piernum = piernum;
    }

    public String getBeamspan() {
        return beamspan;
    }

    public void setBeamspan(String beamspan) {
        this.beamspan = beamspan;
    }

    public String getBeamtype() {
        return beamtype;
    }

    public void setBeamtype(String beamtype) {
        this.beamtype = beamtype;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
