package rwcjom.awit.com.rwcjo_m.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import rwcjom.awit.com.rwcjo_m.dao.Line;
import rwcjom.awit.com.rwcjo_m.dao.BwInfo;
import rwcjom.awit.com.rwcjo_m.dao.SecNews;
import rwcjom.awit.com.rwcjo_m.dao.SiteNews;

import rwcjom.awit.com.rwcjo_m.dao.LineDao;
import rwcjom.awit.com.rwcjo_m.dao.BwInfoDao;
import rwcjom.awit.com.rwcjo_m.dao.SecNewsDao;
import rwcjom.awit.com.rwcjo_m.dao.SiteNewsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lineDaoConfig;
    private final DaoConfig bwInfoDaoConfig;
    private final DaoConfig secNewsDaoConfig;
    private final DaoConfig siteNewsDaoConfig;

    private final LineDao lineDao;
    private final BwInfoDao bwInfoDao;
    private final SecNewsDao secNewsDao;
    private final SiteNewsDao siteNewsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lineDaoConfig = daoConfigMap.get(LineDao.class).clone();
        lineDaoConfig.initIdentityScope(type);

        bwInfoDaoConfig = daoConfigMap.get(BwInfoDao.class).clone();
        bwInfoDaoConfig.initIdentityScope(type);

        secNewsDaoConfig = daoConfigMap.get(SecNewsDao.class).clone();
        secNewsDaoConfig.initIdentityScope(type);

        siteNewsDaoConfig = daoConfigMap.get(SiteNewsDao.class).clone();
        siteNewsDaoConfig.initIdentityScope(type);

        lineDao = new LineDao(lineDaoConfig, this);
        bwInfoDao = new BwInfoDao(bwInfoDaoConfig, this);
        secNewsDao = new SecNewsDao(secNewsDaoConfig, this);
        siteNewsDao = new SiteNewsDao(siteNewsDaoConfig, this);

        registerDao(Line.class, lineDao);
        registerDao(BwInfo.class, bwInfoDao);
        registerDao(SecNews.class, secNewsDao);
        registerDao(SiteNews.class, siteNewsDao);
    }
    
    public void clear() {
        lineDaoConfig.getIdentityScope().clear();
        bwInfoDaoConfig.getIdentityScope().clear();
        secNewsDaoConfig.getIdentityScope().clear();
        siteNewsDaoConfig.getIdentityScope().clear();
    }

    public LineDao getLineDao() {
        return lineDao;
    }

    public BwInfoDao getBwInfoDao() {
        return bwInfoDao;
    }

    public SecNewsDao getSecNewsDao() {
        return secNewsDao;
    }

    public SiteNewsDao getSiteNewsDao() {
        return siteNewsDao;
    }

}
