package rwcjom.awit.com.rwcjo_m.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import rwcjom.awit.com.rwcjo_m.dao.FaceNews;
import rwcjom.awit.com.rwcjo_m.dao.FaceInfo;
import rwcjom.awit.com.rwcjo_m.dao.BrgInfo;
import rwcjom.awit.com.rwcjo_m.dao.PntInfo;
import rwcjom.awit.com.rwcjo_m.dao.PersonInfo;
import rwcjom.awit.com.rwcjo_m.dao.BasePntInfo;
import rwcjom.awit.com.rwcjo_m.dao.Line;
import rwcjom.awit.com.rwcjo_m.dao.BwInfo;
import rwcjom.awit.com.rwcjo_m.dao.SecNews;
import rwcjom.awit.com.rwcjo_m.dao.SiteNews;
import rwcjom.awit.com.rwcjo_m.dao.Line_Extra;
import rwcjom.awit.com.rwcjo_m.dao.Ori_data;

import rwcjom.awit.com.rwcjo_m.dao.FaceNewsDao;
import rwcjom.awit.com.rwcjo_m.dao.FaceInfoDao;
import rwcjom.awit.com.rwcjo_m.dao.BrgInfoDao;
import rwcjom.awit.com.rwcjo_m.dao.PntInfoDao;
import rwcjom.awit.com.rwcjo_m.dao.PersonInfoDao;
import rwcjom.awit.com.rwcjo_m.dao.BasePntInfoDao;
import rwcjom.awit.com.rwcjo_m.dao.LineDao;
import rwcjom.awit.com.rwcjo_m.dao.BwInfoDao;
import rwcjom.awit.com.rwcjo_m.dao.SecNewsDao;
import rwcjom.awit.com.rwcjo_m.dao.SiteNewsDao;
import rwcjom.awit.com.rwcjo_m.dao.Line_ExtraDao;
import rwcjom.awit.com.rwcjo_m.dao.Ori_dataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceNewsDaoConfig;
    private final DaoConfig faceInfoDaoConfig;
    private final DaoConfig brgInfoDaoConfig;
    private final DaoConfig pntInfoDaoConfig;
    private final DaoConfig personInfoDaoConfig;
    private final DaoConfig basePntInfoDaoConfig;
    private final DaoConfig lineDaoConfig;
    private final DaoConfig bwInfoDaoConfig;
    private final DaoConfig secNewsDaoConfig;
    private final DaoConfig siteNewsDaoConfig;
    private final DaoConfig line_ExtraDaoConfig;
    private final DaoConfig ori_dataDaoConfig;

    private final FaceNewsDao faceNewsDao;
    private final FaceInfoDao faceInfoDao;
    private final BrgInfoDao brgInfoDao;
    private final PntInfoDao pntInfoDao;
    private final PersonInfoDao personInfoDao;
    private final BasePntInfoDao basePntInfoDao;
    private final LineDao lineDao;
    private final BwInfoDao bwInfoDao;
    private final SecNewsDao secNewsDao;
    private final SiteNewsDao siteNewsDao;
    private final Line_ExtraDao line_ExtraDao;
    private final Ori_dataDao ori_dataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceNewsDaoConfig = daoConfigMap.get(FaceNewsDao.class).clone();
        faceNewsDaoConfig.initIdentityScope(type);

        faceInfoDaoConfig = daoConfigMap.get(FaceInfoDao.class).clone();
        faceInfoDaoConfig.initIdentityScope(type);

        brgInfoDaoConfig = daoConfigMap.get(BrgInfoDao.class).clone();
        brgInfoDaoConfig.initIdentityScope(type);

        pntInfoDaoConfig = daoConfigMap.get(PntInfoDao.class).clone();
        pntInfoDaoConfig.initIdentityScope(type);

        personInfoDaoConfig = daoConfigMap.get(PersonInfoDao.class).clone();
        personInfoDaoConfig.initIdentityScope(type);

        basePntInfoDaoConfig = daoConfigMap.get(BasePntInfoDao.class).clone();
        basePntInfoDaoConfig.initIdentityScope(type);

        lineDaoConfig = daoConfigMap.get(LineDao.class).clone();
        lineDaoConfig.initIdentityScope(type);

        bwInfoDaoConfig = daoConfigMap.get(BwInfoDao.class).clone();
        bwInfoDaoConfig.initIdentityScope(type);

        secNewsDaoConfig = daoConfigMap.get(SecNewsDao.class).clone();
        secNewsDaoConfig.initIdentityScope(type);

        siteNewsDaoConfig = daoConfigMap.get(SiteNewsDao.class).clone();
        siteNewsDaoConfig.initIdentityScope(type);

        line_ExtraDaoConfig = daoConfigMap.get(Line_ExtraDao.class).clone();
        line_ExtraDaoConfig.initIdentityScope(type);

        ori_dataDaoConfig = daoConfigMap.get(Ori_dataDao.class).clone();
        ori_dataDaoConfig.initIdentityScope(type);

        faceNewsDao = new FaceNewsDao(faceNewsDaoConfig, this);
        faceInfoDao = new FaceInfoDao(faceInfoDaoConfig, this);
        brgInfoDao = new BrgInfoDao(brgInfoDaoConfig, this);
        pntInfoDao = new PntInfoDao(pntInfoDaoConfig, this);
        personInfoDao = new PersonInfoDao(personInfoDaoConfig, this);
        basePntInfoDao = new BasePntInfoDao(basePntInfoDaoConfig, this);
        lineDao = new LineDao(lineDaoConfig, this);
        bwInfoDao = new BwInfoDao(bwInfoDaoConfig, this);
        secNewsDao = new SecNewsDao(secNewsDaoConfig, this);
        siteNewsDao = new SiteNewsDao(siteNewsDaoConfig, this);
        line_ExtraDao = new Line_ExtraDao(line_ExtraDaoConfig, this);
        ori_dataDao = new Ori_dataDao(ori_dataDaoConfig, this);

        registerDao(FaceNews.class, faceNewsDao);
        registerDao(FaceInfo.class, faceInfoDao);
        registerDao(BrgInfo.class, brgInfoDao);
        registerDao(PntInfo.class, pntInfoDao);
        registerDao(PersonInfo.class, personInfoDao);
        registerDao(BasePntInfo.class, basePntInfoDao);
        registerDao(Line.class, lineDao);
        registerDao(BwInfo.class, bwInfoDao);
        registerDao(SecNews.class, secNewsDao);
        registerDao(SiteNews.class, siteNewsDao);
        registerDao(Line_Extra.class, line_ExtraDao);
        registerDao(Ori_data.class, ori_dataDao);
    }
    
    public void clear() {
        faceNewsDaoConfig.getIdentityScope().clear();
        faceInfoDaoConfig.getIdentityScope().clear();
        brgInfoDaoConfig.getIdentityScope().clear();
        pntInfoDaoConfig.getIdentityScope().clear();
        personInfoDaoConfig.getIdentityScope().clear();
        basePntInfoDaoConfig.getIdentityScope().clear();
        lineDaoConfig.getIdentityScope().clear();
        bwInfoDaoConfig.getIdentityScope().clear();
        secNewsDaoConfig.getIdentityScope().clear();
        siteNewsDaoConfig.getIdentityScope().clear();
        line_ExtraDaoConfig.getIdentityScope().clear();
        ori_dataDaoConfig.getIdentityScope().clear();
    }

    public FaceNewsDao getFaceNewsDao() {
        return faceNewsDao;
    }

    public FaceInfoDao getFaceInfoDao() {
        return faceInfoDao;
    }

    public BrgInfoDao getBrgInfoDao() {
        return brgInfoDao;
    }

    public PntInfoDao getPntInfoDao() {
        return pntInfoDao;
    }

    public PersonInfoDao getPersonInfoDao() {
        return personInfoDao;
    }

    public BasePntInfoDao getBasePntInfoDao() {
        return basePntInfoDao;
    }

    public LineDao getLineDao() {
        return lineDao;
    }

    public BwInfoDao getBwInfoDao() {
        return bwInfoDao;
    }

    public SecNewsDao getSecNewsDao() {
        return secNewsDao;
    }

    public SiteNewsDao getSiteNewsDao() {
        return siteNewsDao;
    }

    public Line_ExtraDao getLine_ExtraDao() {
        return line_ExtraDao;
    }

    public Ori_dataDao getOri_dataDao() {
        return ori_dataDao;
    }

}
