package rwcjom.awit.com.rwcjo_m.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FACE_INFO.
 */
public class FaceInfo {

    private String faceid;
    private String jointflag;
    private String structtype;
    private String structname;
    private String structbase;
    private String designatt;
    private String piernum;
    private String dkname;
    private String dkilo;
    private String dchain;
    private String rkname;
    private String rkilo;
    private String rchain;
    private String remark;
    private String f_siteid;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FaceInfo() {
    }

    public FaceInfo(String faceid) {
        this.faceid = faceid;
    }

    public FaceInfo(String faceid, String jointflag, String structtype, String structname, String structbase, String designatt, String piernum, String dkname, String dkilo, String dchain, String rkname, String rkilo, String rchain, String remark, String f_siteid) {
        this.faceid = faceid;
        this.jointflag = jointflag;
        this.structtype = structtype;
        this.structname = structname;
        this.structbase = structbase;
        this.designatt = designatt;
        this.piernum = piernum;
        this.dkname = dkname;
        this.dkilo = dkilo;
        this.dchain = dchain;
        this.rkname = rkname;
        this.rkilo = rkilo;
        this.rchain = rchain;
        this.remark = remark;
        this.f_siteid = f_siteid;
    }

    public String getFaceid() {
        return faceid;
    }

    public void setFaceid(String faceid) {
        this.faceid = faceid;
    }

    public String getJointflag() {
        return jointflag;
    }

    public void setJointflag(String jointflag) {
        this.jointflag = jointflag;
    }

    public String getStructtype() {
        return structtype;
    }

    public void setStructtype(String structtype) {
        this.structtype = structtype;
    }

    public String getStructname() {
        return structname;
    }

    public void setStructname(String structname) {
        this.structname = structname;
    }

    public String getStructbase() {
        return structbase;
    }

    public void setStructbase(String structbase) {
        this.structbase = structbase;
    }

    public String getDesignatt() {
        return designatt;
    }

    public void setDesignatt(String designatt) {
        this.designatt = designatt;
    }

    public String getPiernum() {
        return piernum;
    }

    public void setPiernum(String piernum) {
        this.piernum = piernum;
    }

    public String getDkname() {
        return dkname;
    }

    public void setDkname(String dkname) {
        this.dkname = dkname;
    }

    public String getDkilo() {
        return dkilo;
    }

    public void setDkilo(String dkilo) {
        this.dkilo = dkilo;
    }

    public String getDchain() {
        return dchain;
    }

    public void setDchain(String dchain) {
        this.dchain = dchain;
    }

    public String getRkname() {
        return rkname;
    }

    public void setRkname(String rkname) {
        this.rkname = rkname;
    }

    public String getRkilo() {
        return rkilo;
    }

    public void setRkilo(String rkilo) {
        this.rkilo = rkilo;
    }

    public String getRchain() {
        return rchain;
    }

    public void setRchain(String rchain) {
        this.rchain = rchain;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getF_siteid() {
        return f_siteid;
    }

    public void setF_siteid(String f_siteid) {
        this.f_siteid = f_siteid;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
