package rwcjom.awit.com.rwcjo_m.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import rwcjom.awit.com.rwcjo_m.dao.FaceNews;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FACE_NEWS.
*/
public class FaceNewsDao extends AbstractDao<FaceNews, String> {

    public static final String TABLENAME = "FACE_NEWS";

    /**
     * Properties of entity FaceNews.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FaceId = new Property(0, String.class, "faceId", true, "FACE_ID");
        public final static Property FaceCode = new Property(1, String.class, "faceCode", false, "FACE_CODE");
        public final static Property FaceName = new Property(2, String.class, "faceName", false, "FACE_NAME");
        public final static Property F_siteid = new Property(3, String.class, "f_siteid", false, "F_SITEID");
    };


    public FaceNewsDao(DaoConfig config) {
        super(config);
    }
    
    public FaceNewsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FACE_NEWS' (" + //
                "'FACE_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: faceId
                "'FACE_CODE' TEXT," + // 1: faceCode
                "'FACE_NAME' TEXT," + // 2: faceName
                "'F_SITEID' TEXT);"); // 3: f_siteid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FACE_NEWS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FaceNews entity) {
        stmt.clearBindings();
 
        String faceId = entity.getFaceId();
        if (faceId != null) {
            stmt.bindString(1, faceId);
        }
 
        String faceCode = entity.getFaceCode();
        if (faceCode != null) {
            stmt.bindString(2, faceCode);
        }
 
        String faceName = entity.getFaceName();
        if (faceName != null) {
            stmt.bindString(3, faceName);
        }
 
        String f_siteid = entity.getF_siteid();
        if (f_siteid != null) {
            stmt.bindString(4, f_siteid);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FaceNews readEntity(Cursor cursor, int offset) {
        FaceNews entity = new FaceNews( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // faceId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // faceCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // faceName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // f_siteid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FaceNews entity, int offset) {
        entity.setFaceId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setFaceCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFaceName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setF_siteid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(FaceNews entity, long rowId) {
        return entity.getFaceId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(FaceNews entity) {
        if(entity != null) {
            return entity.getFaceId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
