package rwcjom.awit.com.rwcjo_m.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FACE_NEWS.
 */
public class FaceNews {

    private String faceid;
    private String facecode;
    private String facename;

    public FaceNews() {
    }

    public FaceNews(String faceid) {
        this.faceid = faceid;
    }

    public FaceNews(String faceid, String facecode, String facename) {
        this.faceid = faceid;
        this.facecode = facecode;
        this.facename = facename;
    }

    public String getFaceid() {
        return faceid;
    }

    public void setFaceid(String faceid) {
        this.faceid = faceid;
    }

    public String getFacecode() {
        return facecode;
    }

    public void setFacecode(String facecode) {
        this.facecode = facecode;
    }

    public String getFacename() {
        return facename;
    }

    public void setFacename(String facename) {
        this.facename = facename;
    }

}
