package rwcjom.awit.com.rwcjo_m.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FACE_NEWS.
 */
public class FaceNews {

    private String faceId;
    private String faceCode;
    private String faceName;

    public FaceNews() {
    }

    public FaceNews(String faceId) {
        this.faceId = faceId;
    }

    public FaceNews(String faceId, String faceCode, String faceName) {
        this.faceId = faceId;
        this.faceCode = faceCode;
        this.faceName = faceName;
    }

    public String getFaceId() {
        return faceId;
    }

    public void setFaceId(String faceId) {
        this.faceId = faceId;
    }

    public String getFaceCode() {
        return faceCode;
    }

    public void setFaceCode(String faceCode) {
        this.faceCode = faceCode;
    }

    public String getFaceName() {
        return faceName;
    }

    public void setFaceName(String faceName) {
        this.faceName = faceName;
    }

}
