package rwcjom.awit.com.rwcjo_m.dao;

import java.util.List;
import rwcjom.awit.com.rwcjo_m.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LINE.
 */
public class Line implements java.io.Serializable {

    private String lc;
    private String ln;
    private String f_sectid;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient LineDao myDao;

    private List<BwInfo> bwInfoList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Line() {
    }

    public Line(String lc) {
        this.lc = lc;
    }

    public Line(String lc, String ln, String f_sectid) {
        this.lc = lc;
        this.ln = ln;
        this.f_sectid = f_sectid;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLineDao() : null;
    }

    public String getLc() {
        return lc;
    }

    public void setLc(String lc) {
        this.lc = lc;
    }

    public String getLn() {
        return ln;
    }

    public void setLn(String ln) {
        this.ln = ln;
    }

    public String getF_sectid() {
        return f_sectid;
    }

    public void setF_sectid(String f_sectid) {
        this.f_sectid = f_sectid;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<BwInfo> getBwInfoList() {
        if (bwInfoList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BwInfoDao targetDao = daoSession.getBwInfoDao();
            List<BwInfo> bwInfoListNew = targetDao._queryLine_BwInfoList(lc);
            synchronized (this) {
                if(bwInfoList == null) {
                    bwInfoList = bwInfoListNew;
                }
            }
        }
        return bwInfoList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetBwInfoList() {
        bwInfoList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
