package rwcjom.awit.com.rwcjo_m.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import rwcjom.awit.com.rwcjo_m.dao.Line_Extra;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LINE__EXTRA.
*/
public class Line_ExtraDao extends AbstractDao<Line_Extra, String> {

    public static final String TABLENAME = "LINE__EXTRA";

    /**
     * Properties of entity Line_Extra.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Lc = new Property(0, String.class, "lc", true, "LC");
        public final static Property DevBrand = new Property(1, String.class, "devBrand", false, "DEV_BRAND");
        public final static Property DevType = new Property(2, String.class, "devType", false, "DEV_TYPE");
        public final static Property DevSN = new Property(3, String.class, "devSN", false, "DEV_SN");
        public final static Property Stuffid = new Property(4, String.class, "stuffid", false, "STUFFID");
        public final static Property Stuff_name = new Property(5, String.class, "stuff_name", false, "STUFF_NAME");
        public final static Property Stuff_pwd = new Property(6, String.class, "stuff_pwd", false, "STUFF_PWD");
        public final static Property Temp = new Property(7, String.class, "temp", false, "TEMP");
        public final static Property Weather = new Property(8, String.class, "weather", false, "WEATHER");
        public final static Property Air = new Property(9, String.class, "air", false, "AIR");
        public final static Property Bpntsq = new Property(10, String.class, "bpntsq", false, "BPNTSQ");
        public final static Property Bf_type = new Property(11, String.class, "bf_type", false, "BF_TYPE");
        public final static Property Odate = new Property(12, String.class, "odate", false, "ODATE");
    };

    private DaoSession daoSession;


    public Line_ExtraDao(DaoConfig config) {
        super(config);
    }
    
    public Line_ExtraDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LINE__EXTRA' (" + //
                "'LC' TEXT PRIMARY KEY NOT NULL ," + // 0: lc
                "'DEV_BRAND' TEXT," + // 1: devBrand
                "'DEV_TYPE' TEXT," + // 2: devType
                "'DEV_SN' TEXT," + // 3: devSN
                "'STUFFID' TEXT," + // 4: stuffid
                "'STUFF_NAME' TEXT," + // 5: stuff_name
                "'STUFF_PWD' TEXT," + // 6: stuff_pwd
                "'TEMP' TEXT," + // 7: temp
                "'WEATHER' TEXT," + // 8: weather
                "'AIR' TEXT," + // 9: air
                "'BPNTSQ' TEXT," + // 10: bpntsq
                "'BF_TYPE' TEXT," + // 11: bf_type
                "'ODATE' TEXT);"); // 12: odate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LINE__EXTRA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Line_Extra entity) {
        stmt.clearBindings();
 
        String lc = entity.getLc();
        if (lc != null) {
            stmt.bindString(1, lc);
        }
 
        String devBrand = entity.getDevBrand();
        if (devBrand != null) {
            stmt.bindString(2, devBrand);
        }
 
        String devType = entity.getDevType();
        if (devType != null) {
            stmt.bindString(3, devType);
        }
 
        String devSN = entity.getDevSN();
        if (devSN != null) {
            stmt.bindString(4, devSN);
        }
 
        String stuffid = entity.getStuffid();
        if (stuffid != null) {
            stmt.bindString(5, stuffid);
        }
 
        String stuff_name = entity.getStuff_name();
        if (stuff_name != null) {
            stmt.bindString(6, stuff_name);
        }
 
        String stuff_pwd = entity.getStuff_pwd();
        if (stuff_pwd != null) {
            stmt.bindString(7, stuff_pwd);
        }
 
        String temp = entity.getTemp();
        if (temp != null) {
            stmt.bindString(8, temp);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(9, weather);
        }
 
        String air = entity.getAir();
        if (air != null) {
            stmt.bindString(10, air);
        }
 
        String bpntsq = entity.getBpntsq();
        if (bpntsq != null) {
            stmt.bindString(11, bpntsq);
        }
 
        String bf_type = entity.getBf_type();
        if (bf_type != null) {
            stmt.bindString(12, bf_type);
        }
 
        String odate = entity.getOdate();
        if (odate != null) {
            stmt.bindString(13, odate);
        }
    }

    @Override
    protected void attachEntity(Line_Extra entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Line_Extra readEntity(Cursor cursor, int offset) {
        Line_Extra entity = new Line_Extra( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // lc
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // devBrand
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // devType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // devSN
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // stuffid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // stuff_name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // stuff_pwd
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // temp
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // weather
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // air
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // bpntsq
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // bf_type
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // odate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Line_Extra entity, int offset) {
        entity.setLc(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDevBrand(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDevType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDevSN(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStuffid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStuff_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStuff_pwd(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTemp(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWeather(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setAir(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBpntsq(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setBf_type(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setOdate(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Line_Extra entity, long rowId) {
        return entity.getLc();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Line_Extra entity) {
        if(entity != null) {
            return entity.getLc();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
