package rwcjom.awit.com.rwcjo_m.dao;

import java.util.List;
import rwcjom.awit.com.rwcjo_m.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LINE_EXTRA.
 */
public class LineExtra {

    private String lc;
    private String ltype;
    private String mtype;
    private String devBrand;
    private String devType;
    private String devSN;
    private String stuffid;
    private String stuff_name;
    private String stuff_pwd;
    private String temp;
    private String weather;
    private String air;
    private String bpntsq;
    private String mdate;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient LineExtraDao myDao;

    private List<OriData> oriDataList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LineExtra() {
    }

    public LineExtra(String lc) {
        this.lc = lc;
    }

    public LineExtra(String lc, String ltype, String mtype, String devBrand, String devType, String devSN, String stuffid, String stuff_name, String stuff_pwd, String temp, String weather, String air, String bpntsq, String mdate) {
        this.lc = lc;
        this.ltype = ltype;
        this.mtype = mtype;
        this.devBrand = devBrand;
        this.devType = devType;
        this.devSN = devSN;
        this.stuffid = stuffid;
        this.stuff_name = stuff_name;
        this.stuff_pwd = stuff_pwd;
        this.temp = temp;
        this.weather = weather;
        this.air = air;
        this.bpntsq = bpntsq;
        this.mdate = mdate;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLineExtraDao() : null;
    }

    public String getLc() {
        return lc;
    }

    public void setLc(String lc) {
        this.lc = lc;
    }

    public String getLtype() {
        return ltype;
    }

    public void setLtype(String ltype) {
        this.ltype = ltype;
    }

    public String getMtype() {
        return mtype;
    }

    public void setMtype(String mtype) {
        this.mtype = mtype;
    }

    public String getDevBrand() {
        return devBrand;
    }

    public void setDevBrand(String devBrand) {
        this.devBrand = devBrand;
    }

    public String getDevType() {
        return devType;
    }

    public void setDevType(String devType) {
        this.devType = devType;
    }

    public String getDevSN() {
        return devSN;
    }

    public void setDevSN(String devSN) {
        this.devSN = devSN;
    }

    public String getStuffid() {
        return stuffid;
    }

    public void setStuffid(String stuffid) {
        this.stuffid = stuffid;
    }

    public String getStuff_name() {
        return stuff_name;
    }

    public void setStuff_name(String stuff_name) {
        this.stuff_name = stuff_name;
    }

    public String getStuff_pwd() {
        return stuff_pwd;
    }

    public void setStuff_pwd(String stuff_pwd) {
        this.stuff_pwd = stuff_pwd;
    }

    public String getTemp() {
        return temp;
    }

    public void setTemp(String temp) {
        this.temp = temp;
    }

    public String getWeather() {
        return weather;
    }

    public void setWeather(String weather) {
        this.weather = weather;
    }

    public String getAir() {
        return air;
    }

    public void setAir(String air) {
        this.air = air;
    }

    public String getBpntsq() {
        return bpntsq;
    }

    public void setBpntsq(String bpntsq) {
        this.bpntsq = bpntsq;
    }

    public String getMdate() {
        return mdate;
    }

    public void setMdate(String mdate) {
        this.mdate = mdate;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<OriData> getOriDataList() {
        if (oriDataList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            OriDataDao targetDao = daoSession.getOriDataDao();
            List<OriData> oriDataListNew = targetDao._queryLineExtra_OriDataList(lc);
            synchronized (this) {
                if(oriDataList == null) {
                    oriDataList = oriDataListNew;
                }
            }
        }
        return oriDataList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetOriDataList() {
        oriDataList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
