package rwcjom.awit.com.rwcjo_m.dao;

import rwcjom.awit.com.rwcjo_m.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ORI_DATA.
 */
public class Ori_data {

    private String bffb;
    private String bfpcode;
    private String bfpl;
    private String bfpvalue;
    private String mtime;
    /** Not-null value. */
    private String f_lc;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient Ori_dataDao myDao;

    private Line_Extra line_Extra;
    private String line_Extra__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ori_data() {
    }

    public Ori_data(String bffb, String bfpcode, String bfpl, String bfpvalue, String mtime, String f_lc) {
        this.bffb = bffb;
        this.bfpcode = bfpcode;
        this.bfpl = bfpl;
        this.bfpvalue = bfpvalue;
        this.mtime = mtime;
        this.f_lc = f_lc;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getOri_dataDao() : null;
    }

    public String getBffb() {
        return bffb;
    }

    public void setBffb(String bffb) {
        this.bffb = bffb;
    }

    public String getBfpcode() {
        return bfpcode;
    }

    public void setBfpcode(String bfpcode) {
        this.bfpcode = bfpcode;
    }

    public String getBfpl() {
        return bfpl;
    }

    public void setBfpl(String bfpl) {
        this.bfpl = bfpl;
    }

    public String getBfpvalue() {
        return bfpvalue;
    }

    public void setBfpvalue(String bfpvalue) {
        this.bfpvalue = bfpvalue;
    }

    public String getMtime() {
        return mtime;
    }

    public void setMtime(String mtime) {
        this.mtime = mtime;
    }

    /** Not-null value. */
    public String getF_lc() {
        return f_lc;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setF_lc(String f_lc) {
        this.f_lc = f_lc;
    }

    /** To-one relationship, resolved on first access. */
    public Line_Extra getLine_Extra() {
        String __key = this.f_lc;
        if (line_Extra__resolvedKey == null || line_Extra__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            Line_ExtraDao targetDao = daoSession.getLine_ExtraDao();
            Line_Extra line_ExtraNew = targetDao.load(__key);
            synchronized (this) {
                line_Extra = line_ExtraNew;
            	line_Extra__resolvedKey = __key;
            }
        }
        return line_Extra;
    }

    public void setLine_Extra(Line_Extra line_Extra) {
        if (line_Extra == null) {
            throw new DaoException("To-one property 'f_lc' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.line_Extra = line_Extra;
            f_lc = line_Extra.getLc();
            line_Extra__resolvedKey = f_lc;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
