package rwcjom.awit.com.rwcjo_m.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import rwcjom.awit.com.rwcjo_m.dao.OriData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ORI_DATA.
*/
public class OriDataDao extends AbstractDao<OriData, Long> {

    public static final String TABLENAME = "ORI_DATA";

    /**
     * Properties of entity OriData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Bffb = new Property(1, String.class, "bffb", false, "BFFB");
        public final static Property Bfpcode = new Property(2, String.class, "bfpcode", false, "BFPCODE");
        public final static Property Bfpl = new Property(3, String.class, "bfpl", false, "BFPL");
        public final static Property Bfpvalue = new Property(4, String.class, "bfpvalue", false, "BFPVALUE");
        public final static Property Mtime = new Property(5, String.class, "mtime", false, "MTIME");
        public final static Property F_lc = new Property(6, String.class, "f_lc", false, "F_LC");
    };

    private DaoSession daoSession;

    private Query<OriData> lineExtra_OriDataListQuery;

    public OriDataDao(DaoConfig config) {
        super(config);
    }
    
    public OriDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ORI_DATA' (" + //
                "'ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'BFFB' TEXT," + // 1: bffb
                "'BFPCODE' TEXT," + // 2: bfpcode
                "'BFPL' TEXT," + // 3: bfpl
                "'BFPVALUE' TEXT," + // 4: bfpvalue
                "'MTIME' TEXT," + // 5: mtime
                "'F_LC' TEXT NOT NULL );"); // 6: f_lc
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ORI_DATA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, OriData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bffb = entity.getBffb();
        if (bffb != null) {
            stmt.bindString(2, bffb);
        }
 
        String bfpcode = entity.getBfpcode();
        if (bfpcode != null) {
            stmt.bindString(3, bfpcode);
        }
 
        String bfpl = entity.getBfpl();
        if (bfpl != null) {
            stmt.bindString(4, bfpl);
        }
 
        String bfpvalue = entity.getBfpvalue();
        if (bfpvalue != null) {
            stmt.bindString(5, bfpvalue);
        }
 
        String mtime = entity.getMtime();
        if (mtime != null) {
            stmt.bindString(6, mtime);
        }
        stmt.bindString(7, entity.getF_lc());
    }

    @Override
    protected void attachEntity(OriData entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public OriData readEntity(Cursor cursor, int offset) {
        OriData entity = new OriData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // bffb
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bfpcode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // bfpl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bfpvalue
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // mtime
            cursor.getString(offset + 6) // f_lc
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, OriData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBffb(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBfpcode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBfpl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBfpvalue(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMtime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setF_lc(cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(OriData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(OriData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "oriDataList" to-many relationship of LineExtra. */
    public List<OriData> _queryLineExtra_OriDataList(String f_lc) {
        synchronized (this) {
            if (lineExtra_OriDataListQuery == null) {
                QueryBuilder<OriData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.F_lc.eq(null));
                lineExtra_OriDataListQuery = queryBuilder.build();
            }
        }
        Query<OriData> query = lineExtra_OriDataListQuery.forCurrentThread();
        query.setParameter(0, f_lc);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLineExtraDao().getAllColumns());
            builder.append(" FROM ORI_DATA T");
            builder.append(" LEFT JOIN LINE_EXTRA T0 ON T.'F_LC'=T0.'LC'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected OriData loadCurrentDeep(Cursor cursor, boolean lock) {
        OriData entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        LineExtra lineExtra = loadCurrentOther(daoSession.getLineExtraDao(), cursor, offset);
         if(lineExtra != null) {
            entity.setLineExtra(lineExtra);
        }

        return entity;    
    }

    public OriData loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<OriData> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<OriData> list = new ArrayList<OriData>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<OriData> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<OriData> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
