package rwcjom.awit.com.rwcjo_m.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PNT_INFO.
 */
public class PntInfo {

    private String pointid;
    private String pointnum;
    private String designvalue;
    private String designremark;
    private String inbuiltdate;
    private String seatcode;
    private String remark;
    private String pointcode;
    private String name;
    private String objstate;
    private String f_faceid;

    public PntInfo() {
    }

    public PntInfo(String pointid) {
        this.pointid = pointid;
    }

    public PntInfo(String pointid, String pointnum, String designvalue, String designremark, String inbuiltdate, String seatcode, String remark, String pointcode, String name, String objstate, String f_faceid) {
        this.pointid = pointid;
        this.pointnum = pointnum;
        this.designvalue = designvalue;
        this.designremark = designremark;
        this.inbuiltdate = inbuiltdate;
        this.seatcode = seatcode;
        this.remark = remark;
        this.pointcode = pointcode;
        this.name = name;
        this.objstate = objstate;
        this.f_faceid = f_faceid;
    }

    public String getPointid() {
        return pointid;
    }

    public void setPointid(String pointid) {
        this.pointid = pointid;
    }

    public String getPointnum() {
        return pointnum;
    }

    public void setPointnum(String pointnum) {
        this.pointnum = pointnum;
    }

    public String getDesignvalue() {
        return designvalue;
    }

    public void setDesignvalue(String designvalue) {
        this.designvalue = designvalue;
    }

    public String getDesignremark() {
        return designremark;
    }

    public void setDesignremark(String designremark) {
        this.designremark = designremark;
    }

    public String getInbuiltdate() {
        return inbuiltdate;
    }

    public void setInbuiltdate(String inbuiltdate) {
        this.inbuiltdate = inbuiltdate;
    }

    public String getSeatcode() {
        return seatcode;
    }

    public void setSeatcode(String seatcode) {
        this.seatcode = seatcode;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getPointcode() {
        return pointcode;
    }

    public void setPointcode(String pointcode) {
        this.pointcode = pointcode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getObjstate() {
        return objstate;
    }

    public void setObjstate(String objstate) {
        this.objstate = objstate;
    }

    public String getF_faceid() {
        return f_faceid;
    }

    public void setF_faceid(String f_faceid) {
        this.f_faceid = f_faceid;
    }

}
