package rwcjom.awit.com.rwcjo_m.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SEC_NEWS.
 */
public class SecNews {

    private String sectid;
    private String sectcode;
    private String sectname;

    public SecNews() {
    }

    public SecNews(String sectid) {
        this.sectid = sectid;
    }

    public SecNews(String sectid, String sectcode, String sectname) {
        this.sectid = sectid;
        this.sectcode = sectcode;
        this.sectname = sectname;
    }

    public String getSectid() {
        return sectid;
    }

    public void setSectid(String sectid) {
        this.sectid = sectid;
    }

    public String getSectcode() {
        return sectcode;
    }

    public void setSectcode(String sectcode) {
        this.sectcode = sectcode;
    }

    public String getSectname() {
        return sectname;
    }

    public void setSectname(String sectname) {
        this.sectname = sectname;
    }

}
