package rwcjom.awit.com.rwcjo_m.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SITE_NEWS.
 */
public class SiteNews {

    private String siteid;
    private String sitecode;
    private String sitename;
    private String startsite;
    private String endsite;

    public SiteNews() {
    }

    public SiteNews(String siteid) {
        this.siteid = siteid;
    }

    public SiteNews(String siteid, String sitecode, String sitename, String startsite, String endsite) {
        this.siteid = siteid;
        this.sitecode = sitecode;
        this.sitename = sitename;
        this.startsite = startsite;
        this.endsite = endsite;
    }

    public String getSiteid() {
        return siteid;
    }

    public void setSiteid(String siteid) {
        this.siteid = siteid;
    }

    public String getSitecode() {
        return sitecode;
    }

    public void setSitecode(String sitecode) {
        this.sitecode = sitecode;
    }

    public String getSitename() {
        return sitename;
    }

    public void setSitename(String sitename) {
        this.sitename = sitename;
    }

    public String getStartsite() {
        return startsite;
    }

    public void setStartsite(String startsite) {
        this.startsite = startsite;
    }

    public String getEndsite() {
        return endsite;
    }

    public void setEndsite(String endsite) {
        this.endsite = endsite;
    }

}
